#!/bin/bash

# SCRIPT_DIR="$(dirname "$(realpath "$0")")"

EXECUTABLE="$HOME/.cargo/bin/jump"

if [[ ! -x "$EXECUTABLE" ]]; then
    echo "Script error: Jump-executable not found: $EXECUTABLE"
fi

if [[ $# -eq 1 && "$1" != -* ]]; then
    TARGET_PATH=$("$EXECUTABLE" "$1")

    if [[ -n "$TARGET_PATH" && -d "$TARGET_PATH" ]]; then
        echo "Changing directory to: $TARGET_PATH"
        cd "$TARGET_PATH" 
    else
        echo "Error: Unable to change to directory: $TARGET_PATH"
    fi
else
    "$EXECUTABLE" "$@"
fi
